### ISSUE TITLE
Большое количество ошибок при некотором пороговом значении количества сопрограмм

### ISSUE THREAD

**Issue by batonio** [gridem/Synca#3]
Добрый день.
https://github.com/gridem/Synca/blob/8ae652c8b57f0bb2d4a3145d47a76e1d10498974/examples/server.cpp#L33
Если, к примеру, данный вызов go заменить на
for( int i = 130; i>0; --i ) { go([]{}, net ); }
то вывод valgrind будет содержать большое количество ошибок "Invalid write of size 8"(больше двухста)
Но при этом, при i==129 эти ошибки наблюдаться не будут.
Пороговое значение, конечно же, может отличаться в зависимости от машины, у меня 130 - на ubuntu 14.04 x86_64 gcc 5.4.1, чуть больше трёх тысяч на 17.10 x86_64 gcc 7.2.0.
В обоих случаях BOOST_LIB_VERSION "1_56"
Но остаётся непонятной причина такого поведения valgrind

**Comment by gridem** [comment]
Скорее всего проблема в этом: http://www.boost.org/doc/libs/1_65_1/libs/coroutine/doc/html/coroutine/stack/valgrind.html
Надо предпринимать специальные шаги, чтобы valgrind не ругался.

**Comment by batonio** [comment]
Да, так не ругается, большое спасибо за ключик!
